const admin = [
    {
        id: 1,
        img: 'images.jpg',
        title: 'Крем Geco',
        typesize: 'гр.',
        size: '250',
        code: '0000000001111',
        name: 'Geco',
        brend: 'Geco',
        desc: 'Средство для чистки и мытья рук, паста, крем, скраб',
        price: '92.99',
        category: 'уход за руками'
    },
    {
        id: 2,
        img: 'download01.jpg',
        title: 'Nivea',
        typesize: 'гр.',
        size: '280',
        code: '0000000001112',
        name: 'Nivea',
        brend: 'Nivea',
        desc: 'Средство для чистки и мытья рук, крем',
        price: '80.99',
        category: 'уход за ногами'
        },
        {
        id: 3,
        img: 'images02.jpg',
        title: 'Крем Geco',
        typesize: 'гр.',
        size: '250',
        code: '0000000001113',
        name: 'Geco',
        brend: 'Geco',
        desc: 'Средство для чистки и мытья рук, паста, крем, скраб',
        price: '74.99',
        category: 'уход за телом'
        },
        {
        id: 4,
        img: 'images03.jpg',
        title: 'Крем Geco',
        typesize: 'гр.',
        size: '150',
        code: '0000000001114',
        name: 'Geco',
        brend: 'Geco',
        desc: 'Средство для чистки и мытья рук, паста, крем, скраб',
        price: '80.99',
        category: 'уход за руками'
        },
        {
        id: 5,
        img: 'download02.jpg',
        title: 'Крем Nivea',
        typesize: 'гр.',
        size: '150',
        code: '0000000001111',
        name: 'Nivea',
        brend: 'Nivea',
        desc: 'Средство для чистки и мытья рук',
        price: '99.99',
        category: 'уход за лицом'
        },
        {
        id: 6,
        img: 'download03.jpg',
        title: 'Крем Nivea',
        typesize: 'гр.',
        size: '350',
        code: '0000000001116',
        name: 'Nivea',
        brend: 'Nivea',
        desc: 'Средство для чистки и мытья рук, паста, крем, скраб',
        price: '120.99',
        category: 'уход за лицом'
        },
        {
        id: 7,
        img: 'download04.jpg',
        title: 'Крем Nivea',
        typesize: 'гр.',
        size: '450',
        code: '0000000001111',
        name: 'Nivea',
        brend: 'Nivea',
        desc: 'Средство для чистки и мытья рук',
        price: '250.99',
        category: 'уход за руками'
        },
        {
        id: 8,
        img: 'download17.jpg',
        title: 'Крем Arco',
        typesize: 'гр.',
        size: '230',
        code: '0000000001117',
        name: 'Arco',
        brend: 'Arco',
        desc: 'Средство для чистки , крем',
        price: '200.99',
        category: 'уход за лицом'
        },
        {
        id: 9,
        img: 'download05.jpg',
        title: 'салфетки Paclan',
        typesize: 'шт',
        size: '3',
        code: '0000000001111',
        name: 'Paclan',
        brend: 'Paclan',
        desc: 'Салфетки чистящие',
        price: '55.99',
        category: 'уход за телом'
        },
        {
        id: 10,
        img: 'download06.jpg',
        title: 'Таблетки для посудомоечной машины',
        typesize: 'шт.',
        size: '28',
        code: '0000000001111',
        name: 'Paclan',
        brend: 'Paclan',
        desc: 'Таблетки для посудомоечной машины',
        price: '110.99',
        category: 'уход за телом'
        },
        {
        id: 11,
        img: 'download07.jpg',
        title: 'Paclan',
        typesize: 'гр.',
        size: '250',
        code: '0000000001111',
        name: 'Paclan',
        brend: 'Paclan',
        desc: 'Средство для стирки',
        price: '95.99',
        category: 'уход за телом'
        },
        {
        id: 12,
        img: 'download08.jpg',
        title: 'Крем Bulgari',
        typesize: 'гр.',
        size: '300',
        code: '0000000001111',
        name: 'Bulgari',
        brend: 'Bulgari',
        desc: 'Средство для рук, крем',
        price: '120.99',
        category: 'уход за лицом'
        },
        {
        id: 13,
        img: 'download09.jpg',
        title: 'Духи Bulgari',
        typesize: 'мл',
        size: '300',
        code: '0000000001122',
        name: 'Bulgari',
        brend: 'Bulgari',
        desc: 'Туалетная вода',
        price: '350.99',
        category: 'уход за телом'
        },
        {
        id: 14,
        img: 'download10.jpg',
        title: 'Духи Bulgari',
        typesize: 'мл',
        size: '250',
        code: '0000000001123',
        name: 'Туалетная вода',
        brend: 'Bulgari',
        desc: 'Bulgari',
        price: '108.99',
        category: 'уход за телом'
        },
        {
        id: 15,
        img: 'download11.jpg',
        title: 'Духи Bulgari',
        typesize: 'мл',
        size: '250',
        code: '0000000001111',
        name: 'Bulgari',
        brend: 'Bulgari',
        desc: 'Туалетная вода',
        price: '120.99',
        category: 'уход за телом'
        },
        {
        id: 16,
        img: 'download13.jpg',
        title: 'Крем Arco',
        typesize: 'гр.',
        size: '250',
        code: '0000000001111',
        name: 'Arco',
        brend: 'Arco',
        desc: 'Пена для бритья',
        price: '75.99',
        category: 'уход за телом'
        },
        {
        id: 17,
        img: 'download14.jpg',
        title: 'Крем Arco',
        typesize: 'гр.',
        size: '290',
        code: '0000000001111',
        name: 'Arco',
        brend: 'Arco',
        desc: 'Пена для бритья',
        price: '89.99',
        category: 'уход за телом'
        },
        {
        id: 18,
        img: 'download15.jpg',
        title: 'Крем Arco',
        typesize: 'гр.',
        size: '350',
        code: '0000000001111',
        name: 'Arco',
        brend: 'Arco',
        desc: 'Средство для мытья рук, паста, крем,скраб',
        price: '140.99',
        category: 'уход за ногами'
        },
        {
        id: 19,
        img: 'download16.jpg',
        title: 'Крем Arco',
        typesize: 'гр.',
        size: '250',
        code: '0000000001111',
        name: 'Arco',
        brend: 'Arco',
        desc: 'Средство мытья рук, крем, скраб',
        price: '95.99',
        category: 'уход за телом'
        },
            
]
export default admin
